name: Build Docker image

on:
  push:
    branches: ["main"]

  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    env:
      GITHUB_REGISTRY: /letsbuilders

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract ref name
        run: echo "##[set-output name=ref_name;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref_name

      - uses: docker/setup-buildx-action@v1

      - name: Build and push to GCR and ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ env.GIT_REF }}
          cache-to: type=inline,mode=max
          push: true
          build-args: |
            GIT_REF=${{ steps.extract_ref_name.outputs.ref_name }}
            GITHUB_SHA=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:v1
            ghcr.io/${{ github.repository }}:${{ env.GIT_REF }}
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
