name: Build Docker image

on:
  push:
    branches: ["main"]

  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract ref name
        run: echo "##[set-output name=ref_name;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref_name

      - uses: docker/setup-buildx-action@v2

      - name: Build and push to GCR
        uses: docker/build-push-action@v4
        with:
          context: image
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}:v2
